[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[build.nixpacksPlan.phases.install]
cmds = ["cd backend && pip install -r requirements.txt", "cd frontend && yarn install"]

[build.nixpacksPlan.phases.build]
cmds = ["cd frontend && yarn build"]

[deploy]
startCommand = "cd backend && uvicorn server:app --host 0.0.0.0 --port ${PORT:-8001}"
